---
title: "Watershed_Analysis"
author: "Mwessel"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message=FALSE,warning=FALSE)

library(googlesheets4)
library(googledrive)
library(ggplot2)
library(dplyr)
library(psych)
library(tidyverse)
library(rlang)
library(knitr)
library(lubridate)
library(kableExtra)
library(forcats)
library(reshape2)

# grabs authorization token locally and populates
drive_auth(email="inferential.consulting@gmail.com")
gs4_auth(token = drive_token())
#gs4_auth(email="inferential.consulting@gmail.com")

rm(list = ls())

```

Import Watershed lab data from Googlesheets, clean, transpose, and qualify

```{r WSlab}

# read in watershed lab nutrients and bacteria datasheet 
wslab<-data.frame(read_sheet("https://docs.google.com/spreadsheets/d/1qWWiaY-w2_Z-NJINq-mnOCpXk_fTmuQxA0sgXArYbgg/edit?usp=sharing"))%>%  # col_types = 'cDccccccccccccccccc' c=character D=Date, 
rename(
 Site.ID = Sample.ID,  
 Time2 = Time , 
 Monochlorine.mgl = Monochorine..mg.l.  ,        
 NH4.mgl = Total.Ammonium..NH4.mg.l.  ,          
 NO3.mgl = Nitrate..NO3.mg.l. ,                  
 TN.mgl = Total.Nitrogen...TN.mg.l.,             
 Flow.gsec  = Flow..gal.sec. ,                   
 Ecoli.100ml = Escherichia..Coli..100ml.,        
 Date = Date.of.Monitoring,                      
 NO2.mgl = Nitrite...NO2.mg.l.,                  
 NH3.mgl = Free.Ammonia..NH3.mg.l.,              
 OP.mgl = Orthophosphate..OP.mg.l.,              
 TKN.mgl = Total.Kjeldahl.Nitrogen..TKN.mg.l.,   
 Fcoli.100ml = Fecal.Coliform..100ml.
   )%>%
mutate(Month=month(Date),Year=year(Date),Time=format(strptime(Time2, "%Y-%m-%d %H:%M:%S"),"%H:%M"))%>%
select(-c("Samples.collected.by.","Data.entered.by.","Timestamp","Flow.gsec","Notes.","Month","Year","Time2"))

varit<- c('Monochlorine.mgl','NH4.mgl','NO3.mgl','TN.mgl','Ecoli.100ml','NO2.mgl','NH3.mgl','OP.mgl','TKN.mgl','Fcoli.100ml', 'Ecoli.100ml')

wslab_longer<-pivot_longer(wslab,all_of(varit),names_to = "Param", values_to = "Result",values_transform=list(Result=as.character))%>%
  mutate(disqual =  gsub('\\d|\\.', "", Result))%>% #assign quals as any non digit using regex 
  mutate(disqual_mark = ifelse(disqual=="",0,1))%>% #assign mark to discard quals
  mutate(Result = gsub('<|>|!|?', "", Result))%>%  #remove qual from result 
   mutate(Result=as.numeric(Result),Location = "Watershed") # convert all values to numeric field 
  
 
```


Import Watershed field data from Googlesheets, clean, transpose, and qualify
```{r WSfield}
#names(wsfield)
# read in googlesheet
wsfield<-data.frame(read_sheet("https://docs.google.com/spreadsheets/d/1QA9c1yXKe87fepSy2IrKXdG5lwptLW3lu7fKk-ahDsc/edit?usp=sharing"))%>%
rename(
Date = Date.of.Monitoring             ,
Time2 = Sample.Time                    ,
Collected.by =Samples.collected.by.   ,
Entered.by =Data.entered.by.          ,
Site.ID = Sample.ID                   ,
Temp.c =  Temperature...C.               ,
Conductivity = Conductivity..μS.cm.   ,
DO.mgl = DO..mg.l                     ,
DO.sat = DO....Saturation.            ,
Chla.blue = Chl.a..blue..ug.l.        ,
CDOM = CDOM..ppb.                     ,
Chla.red = Chla.Red..ug.l.            ,
Turb.ntu = Turbidity..NTU.            ,
Sal.psu = Salinity..PSU.              ,
NH3_field = Ammonia..mg.l..Field      ,
Chla.phor = Chlorophyll.aquaphor..ug.l.,
Optical.Brightness = Optical.Brightness,
Notes = Notes.                        ,
Salinty.hand = Salinity..handheld.    ,
Turb.hach = Turbidity..hach.
  )%>%
mutate(Month=month(Date),Year=year(Date),Time=format(strptime(Time2, "%Y-%m-%d %H:%M:%S"),"%H:%M"))%>%
select(-c("Collected.by","Entered.by","Timestamp","Time2","Notes","Month","Year"))%>%
mutate(Site.ID=case_when(Site.ID=="Stream"~"Turtle Stream",TRUE~Site.ID))  


var2<- c("Temp.c","pH", "Conductivity","DO.mgl", "DO.sat", "Chla.blue", "CDOM" , "Chla.red",      
"Turb.ntu", "Sal.psu" , "NH3_field" , "Chla.phor" , "Optical.Brightness"  , "Salinty.hand", "Turb.hach" )              

wsfield_longer<-pivot_longer(wsfield,all_of(var2),names_to = "Param", values_to = "Result",values_transform=list(Result=as.character))%>%
  mutate(disqual =  gsub('\\d|\\.', "", Result))%>% #assign quals as any non digit using regex 
  mutate(disqual_mark = ifelse(disqual=="",0,1))%>% #assign mark to discard quals
  mutate(Result = gsub('<|>|!|?', "", Result))%>%  #remove qual from result
  mutate(Result=as.numeric(Result),Location = "Watershed") # convert all values to numeric field

```

Import Nearshore field data from Googlesheets, clean, transpose, and qualify

```{r Nearshore}
# read in googlesheet
#names(nearshore)

ct<-c("Surf.Lower.Apogee","Surf.Upper.Apogee","Bot.Upper.Apogee","Bot.Lower.Apogee")

nearshore<-data.frame(read_sheet("https://docs.google.com/spreadsheets/d/1O3O3QfYCOVuQg-1aztPyQRtN_W9uO2i4yToqhNFGZ1Y/edit?usp=sharing"))%>%
rename(
 Time2 = Time,
 Surf.Lower.Apogee =Surface...Lower.Apogee.sensor..Channel.B.,
 Surf.Upper.Apogee =Surface..Upper.Apogee.sensor..Channel.A.,
 Bot.Upper.Apogee  =Bottom..Upper.Apogee..Channel.A.,
 Bot.Lower.Apogee  =Bottom...Lower.Apogee..Channel.B.,
 Cloud.Cover = Cloud.Cover.....0...100,
 Surf.Temp   = Surface.Temperature..C.,
 Surf.Sal    = Surface.Salinity..PSU.,
 Surf.DO     = Surface.DO..mg.L.,
 Surf.Turb   = Surface.Turbidity..NTU.,
 Surf.Chl.red= Surface.Chl.red.Fluorescence..µg.L.,
 Bot.DO.sat  = Bottom.DO....saturation.,
 Bot.pH      = Bottom.pH,
 Bot.Chla    = Bottom.Chl.a..Fluorescence..µg.L.,
 Bot.CDOM    = Bottom.CDOM..ppb.,
 Date        = Date.of.Monitoring,
 Data.Entered.By= Data.entered.by.,
 Surf.Time   = Surface.Sample.Time,
 Bot.Time    = Bottom.Sample.Time,
 Surf.DO.Sat = Surface.DO....saturation.,
 Surf.pH     = Surface.pH,
 Surf.Chla   = Surface.Chl.a.Fluorescence..µg.L.,
 Surf.CDOM   = Surface.CDOM..ppb.,
 Bot.Temp    = Bottom.Temperature..C.,
 Bot.Sal     = Bottom.Salinity..PSU.,
 Bot.DO      = Bottom.DO..mg.L.,
 Bot.Turb    = Bottom.Turbidity..NTU.,
 Bot.Chl.red = Bottom.Chl.red.Fluorescence..µg.L.,
 Notes =  Notes..if.applicable.,
 Entero = Enterococci.MPN.100ml..be.sure.to.convert.
# Bot.Cond    = Bottom.Conductivity..Î¼S.cm., these two dont want to work
# Surf.Cond   = Surface.Conductivity..uS.cm.,
  ) %>%
mutate(across(all_of(ct),as.numeric), Normalized_KdPAR=abs(log((Surf.Lower.Apogee/Surf.Upper.Apogee)/(Bot.Lower.Apogee/Bot.Upper.Apogee))))%>%
mutate(Month=month(Date),Year=year(Date),Time=format(strptime(Time2, "%Y-%m-%d %H:%M:%S"),"%H:%M"), Surf.Time=format(strptime(Surf.Time, "%Y-%m-%d %H:%M:%S"),"%H:%M"),
Bot.Time=format(strptime(Bot.Time, "%Y-%m-%d %H:%M:%S"),"%H:%M"))%>%  
select(-c("Measurements.completed.and.samples.collected.","Data.recorded.by.","Data.Entered.By","Sea.State","Wind.Speed" ,"Wind.Direction","Timestamp","Cloud.Cover","Notes","Month","Year","Time2")) 

# pull out sample levels to assign appropriate times

n_bot<-nearshore%>%
  select(c(Site.ID, Date)|starts_with("Bot"))%>%
  rename(Time=Bot.Time)

var3<-c( "Bot.Temp", "Bottom.Conductivity..μS.cm.","Bot.Sal","Bot.DO.sat", "Bot.DO",                    "Bot.pH","Bot.Turb","Bot.Chla","Bot.Chl.red","Bot.CDOM","Bot.Upper.Apogee",       
         "Bot.Lower.Apogee")

bot_long<-pivot_longer(n_bot,all_of(var3),names_to = "Param", values_to = "Result",values_transform=list(Result=as.character))%>%
  mutate(disqual =  gsub('\\d|\\.', "", Result))%>% #assign quals as any non digit using regex 
  mutate(disqual_mark = ifelse(disqual=="",0,1))%>% #assign mark to discard quals
  mutate(Result = gsub('<|>|!|?', "", Result))%>%  #remove qual from result
  mutate(Result=as.numeric(Result),Location = "Nearshore") # convert all values to numeric field

n_surf<-nearshore%>%
  select(c(Site.ID, Date)|starts_with("Surf"))%>%
  rename(Time=Surf.Time)

var4<-c( "Surf.Temp", "Surface.Conductivity..μS.cm.", "Surf.Sal",                    
 "Surf.DO.Sat", "Surf.DO" , "Surf.pH" , "Surf.Turb" , "Surf.Chla",
 "Surf.Chl.red","Surf.CDOM","Surf.Upper.Apogee","Surf.Lower.Apogee")

surf_long<-pivot_longer(n_surf,all_of(var4),names_to = "Param", values_to = "Result",values_transform=list(Result=as.character))%>%
  mutate(disqual =  gsub('\\d|\\.', "", Result))%>% #assign quals as any non digit using regex 
  mutate(disqual_mark = ifelse(disqual=="",0,1))%>% #assign mark to discard quals
  mutate(Result = gsub('<|>|!|?', "", Result))%>%  #remove qual from result
  mutate(Result=as.numeric(Result),Location = "Nearshore") # convert all values to numeric field

# get Entero and KdPar

entero_kd<-nearshore%>%
  select(c(Site.ID, Date,Time,Entero,Normalized_KdPAR))

var5<-c("Entero","Normalized_KdPAR")
 
Ent_long<-pivot_longer(entero_kd,all_of(var5),names_to = "Param", values_to = "Result",values_transform=list(Result=as.character))%>%
  mutate(disqual =  gsub('\\d|\\.', "", Result))%>% #assign quals as any non digit using regex 
  mutate(disqual_mark = ifelse(disqual=="",0,1))%>% #assign mark to discard quals
  mutate(Result = gsub('<|>|!|?', "", Result))%>%  #remove qual from result
  mutate(Result=as.numeric(Result),Location = "Nearshore") # convert all values to numeric field

```


```{r comb}
# combine individual datasets
getwd()
units<-data.frame(read.csv("Parm_units.csv"))

CulWQ_clean<-rbind(wslab_longer,wsfield_longer,bot_long,surf_long,Ent_long)%>%
  select(Location,Site.ID,Date,Time,Param,Result,disqual,disqual_mark)%>%
  mutate(Site.ID = case_when(Site.ID=="Fulladosa  Ramp"~"Fulladosa Ramp",TRUE~Site.ID))%>%
# #mutate(Param=fct_recode(Param, 
# # "Surf.Cond.us/cm" = "Conductivity", "Surf.DO.mgl" = "DO.mgl", "Surf.DO.%sat"= "DO.sat",                    
#   "Surf.Chla.Blue.rfu" = "Chla.blue" , "Surf.CDOM.rfu" =  "CDOM", "Surf.Chla.Red.rfu" = "Chla.red",    
# # "Surf.Turb.ntu"= "Turb.ntu", "Surf.Sal.psu"= "Sal.psu", "NH3.Field" ="NH3_field",      
#    "Bot.Temp.c" ="Bot.Temp", "Bot.Cond.us/cm"="Bottom.Conductivity..μS.cm.", "Bot.Sal.psu"= "Bot.Sal",
#  "Bot.DO.%sat" ="Bot.DO.sat", "Bot.DO.mgl"="Bot.DO","Bot.Turb.ntu" ="Bot.Turb",        "Bot.Chla.Blue.rfu"="Bot.Chla",     #"Bot.Chla.Red.rfu" = "Bot.Chl.red", "Bot.CDOM.rfu" = "Bot.CDOM",
#  "Surf.Temp.c" = "Surf.Temp", "Surf.Cond.us/cm"="Surface.Conductivity..μS.cm.",
#  "Surf.Sal.psu"="Surf.Sal",   "Surf.DO.%sat" = "Surf.DO.Sat","Surf.DO.mgl" = "Surf.DO",
#  "Surf.Turb.ntu" = "Surf.Turb", "Surf.Chla.Blue.rfu"= "Surf.Chla", "Surf.Chla.Red.rfu"= "Surf.Chl.red",
#  "Surf.CDOM.rfu"  ="Surf.CDOM", "Entero.100ml"="Entero"))%>%  
#   mutate(units<-gsub("mgl|ugl|us/cm|\\w+", "", Param, perl = TRUE), whitespace = ",\\s*")%>%
 arrange(Location,Site.ID,Date,Param) 

CulWQ_clean<-left_join(CulWQ_clean,units,by="Param")

# create a timestamp to name dataset
timestamp <- Sys.Date()
filename <- paste0("CulWQ_clean-",timestamp,".rds")

# save file locally 
#setwd(here::here("./analysis"))
saveRDS(CulWQ_clean, file = filename)

 
# identify google drive folder to put data back in as a googlesheet
folder_id <- drive_find(n_max = 10, pattern = "CulWQ_Analysis")$id



filenameonly<-paste0("CulWQ_clean-",timestamp)
gs4_create(filenameonly,
  sheets =CulWQ_clean)

# this will not overwrite a file
 drive_mv(file = filenameonly, path = as_id(folder_id))

```







