
page_navbar(
  title = "NOAA Culebra LBSP Dashboard",
  window_title = "Culebra LBSP",
  id = "nav",
  sidebar = sidebar(
    id = "sidebar",
    width = 320,
    open = FALSE,
    conditionalPanel(
      condition = 'input.nav == "Dashboard"',
      selectInput(inputId = 'dataset', label = "Dataset", 
                  choices = c("Routine Water Quality", "Special Nutrient Collection", "Seagrass"), 
                  selected = "Routine Water Quality"),
      conditionalPanel(condition = 'input.dataset != "Seagrass"',
                       selectInput(inputId = 'location', label = "Location", 
                                   choices = c("Nearshore", "Watershed"), selected = "Nearshore")),
      conditionalPanel(condition = 'input.dataset != "Seagrass" & input.location == "Nearshore"',
                       selectInput(inputId = 'level', label = 'Sample Level', 
                                   choices = c("Surface", "Bottom", "N/A"))),
      conditionalPanel(condition = 'input.panel != "Tile Plot"',
                       selectInput(inputId = 'parameter', label = 'Parameter', choices = NULL)),
      conditionalPanel(condition = 'input.dataset == "Seagrass" | input.location == "Nearshore"',
                       pickerInput(inputId = "group", label = "Treatment Group", multiple = TRUE, 
                                   choices = names(ns_grp_colors), selected = names(ns_grp_colors))),
      pickerInput(inputId = "stations", label = "Stations", multiple = TRUE, choices = ns_stations, 
                  selected = unlist(ns_stations), options = list(`actions-box` = TRUE, size = 8)),
      conditionalPanel(condition = 'input.dataset != "Seagrass"',
                       sliderTextInput(inputId = "date_range", label = "Date Range", choices = c("Jan 2023", "May 2024"), 
                                       selected = c("Jan 2023", "May 2024"))),
      conditionalPanel(condition = 'input.dataset == "Seagrass"',
                       radioButtons("sg_year", label = "Year", inline = TRUE, 
                                    choices = c(2022, 2014), selected = 2022)),
      conditionalPanel(condition = 'input.panel == "Bar Plot" | input.panel == "Tile Plot" | input.panel == "Map"',
                       selectInput(inputId = "stat", "Statistic", choices = c("Minimum", "Median", "Maximum"),
                                   selected = "Median")),
      downloadButton("downloadFilteredData", "Download Filtered Data"),
      downloadButton("downloadAllData", "Download All Data")
    )
  ),
  nav_panel("About",
            p("Testing...")),
  nav_panel("Dashboard",
            navset_card_underline(
              id = "panel",
              title = "All data are provisional and subject to revision",
              nav_panel("Time Series Plot", plotlyOutput("tsPlot")),
              nav_panel("Box Plot", plotlyOutput("boxPlot")),
              nav_panel("Bar Plot", plotlyOutput("barPlot")),
              nav_panel("Tile Plot", plotlyOutput("tilePlot")),
              nav_panel("Map", leafletOutput("map")),
              nav_panel("Table", DT::dataTableOutput("table")),
            )
  )
)